version: "3"
services:
  rabbitque:
    container_name: rabbitque
    build: ./RabbitMQService
    restart: always
    ports: 
      - "7777:7777"
    expose:
      - 7777
  restaurant:
    container_name: restaurant
    build: ./RestaurantService
    restart: always
    ports:
      - "3000:3000"
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on:
      - mongo
    links:
      - mongo
  order:
    container_name: order
    build: ./OrderService
    restart: always
    ports:
      - "3001:3001"
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on:
      - mongo
    links:
      - mongo
      - rabbitque
  mongo:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log/mongodb/mongodb.log
    volumes:
      - "mongodbdata:/data/db"
    ports:
      - "27017:27017"
    expose:
      - 27017
    command: "mongod"
volumes:
  mongodbdata:
    external: true